// Auto-generated by scripts/sync-story-media.mjs — do not edit manually.
// Re-run: npm run sync:media (also runs automatically before dev/build)

export const STORY_MEDIA_CACHE_VERSION = 1779376519350;

export const storyImagesBySlug: Record<string, string[]> = {
  "day-we-met": [
    "/images/childhood/story/day-we-met/1.png?v=1779365509719",
    "/images/childhood/story/day-we-met/2.png?v=1779365552580",
    "/images/childhood/story/day-we-met/3.png?v=1779365585388",
    "/images/childhood/story/day-we-met/4.png?v=1779365609929"
  ],
  "first-conversation": [
    "/images/childhood/story/first-conversation/1.png?v=1779365670134",
    "/images/childhood/story/first-conversation/2.png?v=1779365749713",
    "/images/childhood/story/first-conversation/3.png?v=1779365800443",
    "/images/childhood/story/first-conversation/4.png?v=1779365885132"
  ],
  "first-photo": [
    "/images/childhood/story/first-photo/1.png?v=1779366175818",
    "/images/childhood/story/first-photo/2.png?v=1779366138410",
    "/images/childhood/story/first-photo/3.png?v=1779366215618",
    "/images/childhood/story/first-photo/4.png?v=1779366258178"
  ],
  "first-fight": [
    "/images/childhood/story/first-fight/1.png?v=1779375963661",
    "/images/childhood/story/first-fight/2.png?v=1779366007060",
    "/images/childhood/story/first-fight/3.png?v=1779366007872",
    "/images/childhood/story/first-fight/4.png?v=1779366008466"
  ],
  "first-trip": [
    "/images/childhood/story/first-trip/1.png?v=1779366602973",
    "/images/childhood/story/first-trip/2.png?v=1779366635317",
    "/images/childhood/story/first-trip/3.png?v=1779366660160",
    "/images/childhood/story/first-trip/4.png?v=1779366695445"
  ],
  "fell-for-you": [
    "/images/childhood/story/fell-for-you/1.png?v=1779366761341",
    "/images/childhood/story/fell-for-you/2.png?v=1779366781371",
    "/images/childhood/story/fell-for-you/3.png?v=1779366878095",
    "/images/childhood/story/fell-for-you/4.png?v=1779366897915"
  ],
  "craziest-memory": [
    "/images/childhood/story/craziest-memory/1.png?v=1779367081730",
    "/images/childhood/story/craziest-memory/2.png?v=1779367184834",
    "/images/childhood/story/craziest-memory/3.png?v=1779367207269",
    "/images/childhood/story/craziest-memory/4.png?v=1779367237931"
  ],
  "you-became-home": [
    "/images/childhood/story/you-became-home/1.png?v=1778961278384",
    "/images/childhood/story/you-became-home/2.png?v=1778961337359",
    "/images/childhood/story/you-became-home/3.png?v=1778961418973",
    "/images/childhood/story/you-became-home/4.png?v=1778961582769"
  ]
};

export const storySongsBySlug: Record<string, string> = {
  "day-we-met": "/music/story/day-we-met/song.mp3?v=1779376451439",
  "first-conversation": "/music/story/first-conversation/song.mp3?v=1779376307857",
  "first-photo": "/music/story/first-photo/song.mp3?v=1779376384806",
  "first-fight": "/music/story/first-fight/song.mp3?v=1779376105090",
  "first-trip": "/music/story/first-trip/song.mp3?v=1779376257551",
  "fell-for-you": "/music/story/fell-for-you/song.mp3?v=1779376493390",
  "craziest-memory": "/music/story/craziest-memory/song.mp3?v=1779376519350",
  "you-became-home": "/music/story/you-became-home/song.mp3?v=1779376416366"
};
